version: '3'
env:
  GOBIN: { sh: pwd }
  # OTEL_TRACES_EXPORTER: console
  OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:14318
  OTEL_EXPORTER_OTLP_HEADERS: "uptrace-dsn=http://project2_secret_token@localhost:14318?grpc=14317"
  OTEL_EXPORTER_OTLP_COMPRESSION: gzip
  OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION: BASE2_EXPONENTIAL_BUCKET_HISTOGRAM
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: DELTA
  OTEL_TRACES_SAMPLER: parentbased_traceidratio
  OTEL_TRACES_SAMPLER_ARG: 0.001

tasks:
  gateway:
    cmds:
      - KOD_CONFIG=./example/gateway/config.yaml go run ./cmd/gateway

  deps:
    deps:
      - constructsserver
      - optionsserver

  constructsserver:
    cmds:
      - go run ./example/gateway/constructsserver 
  
  optionsserver:
    cmds:
      - go run ./example/gateway/optionsserver  

  bench:
    cmds:
      - "ab -n 50000 -kc 100 -T 'application/json' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept: application/json' -H 'DNT: 1' -H 'Origin: http://localhost:8080' -p test/post2.json http://localhost:8080/query"

  test:
    cmds:
      - go test -race -cover -coverprofile=coverage.out.tmp -covermode=atomic ./...
    sources:
      - "**/**.go"
    generates:
      - coverage.out.tmp
  test:coverage:
    cmds:
      - cat coverage.out.tmp | egrep -v "kod_|.pb.go|_test.go|example/gateway|pkg/types/|/test" > coverage.out
      - go tool cover -func=coverage.out
      - rm coverage.out.tmp coverage.out
    deps:
      - test
