address: ":8080"

pyroscope:
  enable: true
  serverAddress: "http://localhost:4040"

grpc:
  services:
    - address: "localhost:8081"
      reflection: true
    - address: "localhost:8082"
      reflection: true

graphql:
  disable: false
  playground: true
