graphql:
  address: ":8080"
  disable: false
  playground: true

engine:
  generateUnboundMethod: false
  rateLimit: true
  circuitBreaker: true
  queryCache: true
  singleFlight: true
  pyroscope:
    enable: true
    serverAddress: "http://localhost:4040"

grpc:
  etcd: 
    endpoints: ["localhost:2379"]
    timeout: "3s"

  services:
    - target: "etcd:///local/optionsserver/grpc"
      timeout: "1s"
    - target: "etcd:///local/constructsserver/grpc"
      timeout: "1s"
