address: ":8080"

engine:
  generate_unbound_method: false
  pyroscope:
    enable: true
    serverAddress: "http://localhost:4040"

grpc:
  services:
    - address: "etcd:///local/optionsserver/grpc"
      reflection: true
    - address: "etcd:///local/constructsserver/grpc"
      reflection: true

graphql:
  disable: false
  playground: true
