graphql:
  address: ":8080"
  disable: false
  playground: true

engine:
  generate_unbound_method: false
  rate_limit: true
  circuit_breaker: true
  query_cache: true
  single_flight: true
  pyroscope:
    enable: true
    server_address: "http://localhost:4040"

grpc:
  etcd: 
    endpoints: ["localhost:2379"]
    timeout: "3s"

  services:
    - target: "etcd:///local/optionsserver/grpc"
      timeout: "1s"
    - target: "etcd:///local/constructsserver/grpc"
      timeout: "1s"
