name: Build and Test

on:
 push:
   branches:
     - 'main'
 pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["stable"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: docker-compose
        run: docker-compose -f deployment/docker-compose.yml up -d

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
          cache: true

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: generate and test
        run: |
            task

      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage.out.final # optional
          token: ${{ secrets.CODECOV_TOKEN }}